*** Settings ***
Documentation       Check that the members of Table 5.2.9-2 are ignored when a client
...                 provides them. CIM 009 clause 5.2.9, after Table 5.2.9-1: "The
...                 members (defined by Table 5.2.9-2) of the CSourceRegistration data
...                 structure are also defined. They are read-only and shall be
...                 automatically generated by NGSI-LD implementations. In the event
...                 that they are provided (in update or create operations) NGSI-LD
...                 implementations shall ignore them." The members are lastFailure,
...                 status, timesFailed, timesSent and lastSuccess.
...
...                 Antares extension TP — the official TPs never send them.

Library             RequestsLibrary
Library             Collections
Resource            ${EXECDIR}/resources/ApiUtils/Common.resource
Resource            ${EXECDIR}/resources/ApiUtils/ContextSourceRegistration.resource
Resource            ${EXECDIR}/resources/AssertionUtils.resource


*** Variables ***
@{READ_ONLY_MEMBERS}    lastFailure    status    timesFailed    timesSent    lastSuccess


*** Test Cases ***
5292_01_01 Table 5.2.9-2 Members Provided At Creation Are Ignored
    [Documentation]    A registration created with a forward history keeps none of it
    [Tags]    csr-create    5_2_9    since_v1.9.1
    ${id}=    Generate Random CSR Id
    ${body}=    Registration With A Claimed History    ${id}
    ${response}=    POST
    ...    url=${url}/${CONTEXT_SOURCE_REGISTRATION_ENDPOINT_PATH}
    ...    data=${body}
    ...    headers=${{ {"Content-Type": "application/json"} }}
    ...    expected_status=any
    Check Response Status Code    201    ${response.status_code}
    Registration Carries No Claimed History    ${id}
    Delete Context Source Registration    ${id}

5292_01_02 Table 5.2.9-2 Members Provided At Update Are Ignored
    [Documentation]    The same members through the 5.9.3 merge patch
    [Tags]    csr-update    5_2_9    since_v1.9.1
    ${id}=    Generate Random CSR Id
    ${clean}=    Evaluate
    ...    json.dumps({"id": $id, "type": "ContextSourceRegistration", "endpoint": "http://peer.example/ngsi-ld/v1", "information": [{"entities": [{"type": "Building"}]}]})
    ...    modules=json
    ${response}=    POST
    ...    url=${url}/${CONTEXT_SOURCE_REGISTRATION_ENDPOINT_PATH}
    ...    data=${clean}
    ...    headers=${{ {"Content-Type": "application/json"} }}
    ...    expected_status=any
    Check Response Status Code    201    ${response.status_code}
    ${patch}=    Evaluate
    ...    json.dumps({"lastFailure": "2035-01-01T00:00:00Z", "status": "ok", "timesFailed": 0, "timesSent": 9000, "lastSuccess": "2035-01-01T00:00:00Z"})
    ...    modules=json
    ${response}=    PATCH
    ...    url=${url}/${CONTEXT_SOURCE_REGISTRATION_ENDPOINT_PATH}/${id}
    ...    data=${patch}
    ...    headers=${{ {"Content-Type": "application/json"} }}
    ...    expected_status=any
    Check Response Status Code    204    ${response.status_code}
    Registration Carries No Claimed History    ${id}
    Delete Context Source Registration    ${id}


*** Keywords ***
Registration With A Claimed History
    [Arguments]    ${id}
    ${body}=    Evaluate
    ...    json.dumps({"id": $id, "type": "ContextSourceRegistration", "endpoint": "http://peer.example/ngsi-ld/v1", "information": [{"entities": [{"type": "Building"}]}], "lastFailure": "2035-01-01T00:00:00Z", "status": "ok", "timesFailed": 0, "timesSent": 9000, "lastSuccess": "2035-01-01T00:00:00Z"})
    ...    modules=json
    RETURN    ${body}

Registration Carries No Claimed History
    [Arguments]    ${id}
    ${response}=    GET
    ...    url=${url}/${CONTEXT_SOURCE_REGISTRATION_ENDPOINT_PATH}/${id}
    ...    expected_status=any
    Check Response Status Code    200    ${response.status_code}
    ${served}=    Set Variable    ${response.json()}
    FOR    ${member}    IN    @{READ_ONLY_MEMBERS}
        ${claimed}=    Get From Dictionary    ${served}    ${member}    ${None}
        Should Be Equal    ${claimed}    ${None}
        ...    msg=the read-only member ${member} was taken from the client: ${served}
    END
