// SPDX-License-Identifier: EUPL-1.2
//! Table 5.2.9-2: the forward history a Context Source Registration carries.
//!
//! 5.2.9, after Table 5.2.9-1: the members of Table 5.2.9-2 "are read-only
//! and shall be automatically generated by NGSI-LD implementations". The
//! table defines `timesSent` as the "number of times that the registration
//! triggered a distributed operation, including failed attempts",
//! `timesFailed` as the number that failed, `lastFailure` as the instant a
//! failure — "for instance, in the HTTP binding, an HTTP response code other
//! than 2xx" — was returned, `lastSuccess` as the instant of the last
//! successful operation ("created on first successful operation"), and
//! `status` as `"ok"` when the LAST attempt succeeded and `"failed"` when it
//! did not.
//!
//! So the counters are asserted from outside, through a forward to a mock
//! Context Source whose answer this file chooses, and read back through the
//! 5.10.1 retrieve — a member the broker writes but never serves is no
//! better than one it never wrote.

use antares_api::AppState;
use axum::body::Body;
use axum::http::{Request, StatusCode};
use serde_json::Value;
use std::io::{Read, Write};
use tower::ServiceExt;

/// A mock Context Source that answers every request with `status`, and an
/// empty entity array when that status is a 2xx (a 5xx body is never read).
fn source(status: u16) -> u16 {
    let body = "[]";
    let reason = if status == 200 { "OK" } else { "Server Error" };
    let reply = format!(
        "HTTP/1.1 {status} {reason}\r\nContent-Type: application/json\r\n\
         Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
        body.len()
    );
    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("bind");
    let port = listener.local_addr().expect("addr").port();
    std::thread::spawn(move || {
        for stream in listener.incoming() {
            let Ok(mut s) = stream else { continue };
            let reply = reply.clone();
            std::thread::spawn(move || {
                let mut buf = [0u8; 8192];
                let _ = s.read(&mut buf);
                let _ = s.write_all(reply.as_bytes());
            });
        }
    });
    port
}

/// 4.14 keeps every operation inside one tenant; `None` is the default one.
fn tenanted(
    req: axum::http::request::Builder,
    tenant: Option<&str>,
) -> axum::http::request::Builder {
    match tenant {
        Some(t) => req.header("NGSILD-Tenant", t),
        None => req,
    }
}

async fn register(st: &AppState, id: &str, port: u16, tenant: Option<&str>) {
    let body = serde_json::json!({
        "id": id,
        "type": "ContextSourceRegistration",
        "mode": "inclusive",
        "operations": ["queryEntity"],
        "information": [{"entities": [{"type": "Vehicle"}]}],
        "endpoint": format!("http://127.0.0.1:{port}"),
    })
    .to_string();
    let res = antares_api::router(st.clone())
        .oneshot(
            tenanted(Request::post("/ngsi-ld/v1/csourceRegistrations"), tenant)
                .header("Content-Type", "application/json")
                .header("Content-Length", body.len())
                .body(Body::from(body))
                .expect("request"),
        )
        .await
        .expect("response");
    assert_eq!(res.status(), StatusCode::CREATED, "registration create");
}

/// One distributed query, which the registration above matches.
async fn query(st: &AppState, tenant: Option<&str>) {
    let res = antares_api::router(st.clone())
        .oneshot(
            tenanted(Request::get("/ngsi-ld/v1/entities?type=Vehicle"), tenant)
                .body(Body::empty())
                .expect("request"),
        )
        .await
        .expect("response");
    assert!(
        res.status().is_success(),
        "4.3.6.4 keeps a failed forward a warning on a successful answer, \
         not an error: {}",
        res.status()
    );
}

/// Read the registration back the way a client does (5.10.1).
async fn retrieve(st: &AppState, id: &str, tenant: Option<&str>) -> Value {
    let res = antares_api::router(st.clone())
        .oneshot(
            tenanted(
                Request::get(format!("/ngsi-ld/v1/csourceRegistrations/{id}")),
                tenant,
            )
            .body(Body::empty())
            .expect("request"),
        )
        .await
        .expect("response");
    assert_eq!(res.status(), StatusCode::OK, "retrieve");
    let bytes = axum::body::to_bytes(res.into_body(), usize::MAX)
        .await
        .expect("body");
    serde_json::from_slice(&bytes).expect("json")
}

/// A DateTime per clause 4.6.3, which is what both stamps are declared as:
/// `YYYY-MM-DDThh:mm:ss[.fff]Z`. A counter written as a bare number, an
/// empty string or a local time would pass an `is_string` test and fail a
/// client that parses it.
fn is_datetime(v: Option<&Value>) -> bool {
    v.and_then(Value::as_str).is_some_and(|s| {
        let b = s.as_bytes();
        b.len() >= 20
            && b[4] == b'-'
            && b[7] == b'-'
            && b[10] == b'T'
            && b[13] == b':'
            && b[16] == b':'
            && b[b.len() - 1] == b'Z'
    })
}

/// A source that answers 2xx: `timesSent` moves, `lastSuccess` is created on
/// the first successful operation, `status` is "ok", and neither failure
/// member exists — cardinality 0..1 means a member appears when it has
/// something to say, and a registration that has never failed has not.
#[tokio::test(flavor = "multi_thread")]
async fn a_successful_forward_moves_times_sent_and_last_success() {
    antares_jsonld::allow_private_egress(true);
    let id = "urn:ngsi-ld:ContextSourceRegistration:counters-ok";
    let st = AppState::new("counters-ok".into());
    register(&st, id, source(200), None).await;

    let before = retrieve(&st, id, None).await;
    assert!(
        before.get("timesSent").is_none() && before.get("status").is_none(),
        "a registration that has forwarded nothing carries no history: {before}"
    );

    query(&st, None).await;
    let one = retrieve(&st, id, None).await;
    assert_eq!(one["timesSent"], 1, "the first forward is counted: {one}");
    assert_eq!(
        one["status"], "ok",
        "a 2xx leaves the registration ok: {one}"
    );
    assert!(
        is_datetime(one.get("lastSuccess")),
        "lastSuccess is a 4.6.3 DateTime: {one}"
    );
    assert!(
        one.get("timesFailed").is_none() && one.get("lastFailure").is_none(),
        "a registration that has only succeeded carries no failure: {one}"
    );

    query(&st, None).await;
    let two = retrieve(&st, id, None).await;
    assert_eq!(
        two["timesSent"], 2,
        "timesSent accumulates, it does not reset: {two}"
    );
}

/// A source that answers 500: the table's own failure definition. Every
/// failure counts in BOTH counters — `timesSent` is "including failed
/// attempts" — and `status` names the last attempt.
#[tokio::test(flavor = "multi_thread")]
async fn a_failed_forward_moves_times_failed_and_last_failure() {
    antares_jsonld::allow_private_egress(true);
    let id = "urn:ngsi-ld:ContextSourceRegistration:counters-bad";
    let st = AppState::new("counters-bad".into());
    register(&st, id, source(500), None).await;

    query(&st, None).await;
    let one = retrieve(&st, id, None).await;
    assert_eq!(
        one["timesSent"], 1,
        "a failed attempt is still an attempt (Table 5.2.9-2): {one}"
    );
    assert_eq!(one["timesFailed"], 1, "the failure is counted: {one}");
    assert_eq!(one["status"], "failed", "status names the attempt: {one}");
    assert!(
        is_datetime(one.get("lastFailure")),
        "lastFailure is a 4.6.3 DateTime: {one}"
    );
    assert!(
        one.get("lastSuccess").is_none(),
        "lastSuccess is created on the first SUCCESSFUL operation: {one}"
    );
}

/// The two histories are per registration and per tenant: 4.14 keeps a
/// tenant's registrations "in isolation", and 5.5.10 makes the id
/// client-chosen per tenant, so the same id in two tenants is two
/// registrations with two histories.
#[tokio::test(flavor = "multi_thread")]
async fn one_registration_s_forwards_never_land_on_another() {
    antares_jsonld::allow_private_egress(true);
    let good = "urn:ngsi-ld:ContextSourceRegistration:counters-a";
    let bad = "urn:ngsi-ld:ContextSourceRegistration:counters-b";
    let st = AppState::new("counters-two".into());
    register(&st, good, source(200), None).await;
    register(&st, bad, source(500), None).await;

    query(&st, None).await;
    let a = retrieve(&st, good, None).await;
    let b = retrieve(&st, bad, None).await;
    assert_eq!(a["timesSent"], 1, "{a}");
    assert_eq!(a["status"], "ok", "{a}");
    assert!(a.get("timesFailed").is_none(), "{a}");
    assert_eq!(b["timesSent"], 1, "{b}");
    assert_eq!(b["status"], "failed", "{b}");
    assert_eq!(b["timesFailed"], 1, "{b}");
}

/// 4.14 keeps a tenant's information "in isolation", and 5.5.10 makes the
/// registration id client-chosen per tenant — so the same id in two tenants
/// is two registrations, and a forward one tenant triggered may not appear
/// in the other's history. `record_forward` is tenant-keyed like every other
/// store operation, and this holds it there.
#[tokio::test(flavor = "multi_thread")]
async fn one_tenant_s_forwards_never_land_on_another_tenant_s_registration() {
    antares_jsonld::allow_private_egress(true);
    let id = "urn:ngsi-ld:ContextSourceRegistration:counters-shared-id";
    let st = AppState::new("counters-tenants".into());
    register(&st, id, source(200), Some("busy")).await;
    register(&st, id, source(200), Some("quiet")).await;

    query(&st, Some("busy")).await;
    query(&st, Some("busy")).await;

    let busy = retrieve(&st, id, Some("busy")).await;
    let quiet = retrieve(&st, id, Some("quiet")).await;
    assert_eq!(
        busy["timesSent"], 2,
        "the busy tenant forwarded twice: {busy}"
    );
    assert!(
        quiet.get("timesSent").is_none() && quiet.get("status").is_none(),
        "another tenant's forwards were booked here: {quiet}"
    );
}
